# -*- coding: utf-8 -*-
"""Copy of 4A-REYES-EXER2-MP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXk51OnVe1VpbWBXoi71zQ-_GkA_zEa7

# Module 2.0: Feature Extraction and Object Detection

# Machine Problem 3
"""

import cv2
import matplotlib.pyplot as plt

# Load the two images
image1 = cv2.imread('/content/zhang hao.jfif')
image2 = cv2.imread('/content/zhang hao 1.jfif')

# Convert both images to grayscale
gray_image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray_image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Initialize the detectors for SIFT, SURF, and ORB
sift = cv2.SIFT_create()
surf = cv2.xfeatures2d.SURF_create(400)  # Hessian threshold set to 400
orb = cv2.ORB_create()

# Function to detect keypoints and compute descriptors for a given detector
def detect_and_compute(detector, gray_image):
    keypoints, descriptors = detector.detectAndCompute(gray_image, None)
    return keypoints, descriptors

# Detect keypoints and compute descriptors using SIFT
keypoints1_sift, descriptors1_sift = detect_and_compute(sift, gray_image1)
keypoints2_sift, descriptors2_sift = detect_and_compute(sift, gray_image2)

# Detect keypoints and compute descriptors using SURF
keypoints1_surf, descriptors1_surf = detect_and_compute(surf, gray_image1)
keypoints2_surf, descriptors2_surf = detect_and_compute(surf, gray_image2)

# Detect keypoints and compute descriptors using ORB
keypoints1_orb, descriptors1_orb = detect_and_compute(orb, gray_image1)
keypoints2_orb, descriptors2_orb = detect_and_compute(orb, gray_image2)

# Function to draw keypoints on the image
def draw_keypoints(image, keypoints, title):
    image_with_keypoints = cv2.drawKeypoints(image, keypoints, None)
    plt.imshow(cv2.cvtColor(image_with_keypoints, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.show()

# Draw keypoints detected by SIFT on both images
draw_keypoints(image1, keypoints1_sift, "SIFT Keypoints - Image 1")
draw_keypoints(image2, keypoints2_sift, "SIFT Keypoints - Image 2")

# Draw keypoints detected by SURF on both images
draw_keypoints(image1, keypoints1_surf, "SURF Keypoints - Image 1")
draw_keypoints(image2, keypoints2_surf, "SURF Keypoints - Image 2")

# Draw keypoints detected by ORB on both images
draw_keypoints(image1, keypoints1_orb, "ORB Keypoints - Image 1")
draw_keypoints(image2, keypoints2_orb, "ORB Keypoints - Image 2")